### ISSUE TITLE
Viewer is not able to load report from URL

### ISSUE THREAD

**Issue by lock9** [Red4Sec/neo-resilience#2]
Hi,

http://neocharts.red4sec.com/viewer/?u=https://s3.us-east-2.amazonaws.com/neoresilience.neoexperimental/test-reports/1569267126/report.json

The URL is valid:
https://s3.us-east-2.amazonaws.com/neoresilience.neoexperimental/test-reports/1569267126/report.json

Thanks 😘

**Comment by belane** [comment]
It's because missing CORS policy in the `neoresilience.neoexperimental` bucket, check your browser's console.

If you download the file and load it from **"Load from files"** works well.


_* https://docs.aws.amazon.com/AmazonS3/latest/user-guide/add-cors-configuration.html_

**Comment by lock9** [comment]
<img width="677" alt="pikachu" src="https://user-images.githubusercontent.com/38396062/65839921-6d90b180-e2e8-11e9-9ab5-950011730f11.png">

**Comment by lock9** [comment]
@belane why the charts are not appearing like in the other tests? Can you check the url again? It can load the file but I can't understand what is going on 🤔

**Comment by belane** [comment]
@lock9 is because your test is too sort, less than 4 blocks, and Charts Viewer removes the first 4 blocks (warm-up phase) to have uniform values, skipping first blocks were the consensus is syncing.
